-- ==========================================
-- Auto-generated Supabase PostgreSQL Schema
-- Generated from Firebase Firestore Export
-- ==========================================

CREATE TABLE IF NOT EXISTS "academies" (
  "id" TEXT PRIMARY KEY,
  "academy_name" TEXT,
  "description" TEXT,
  "logo" TEXT,
  "coverImage" TEXT,
  "founding_year" TEXT,
  "academy_type" TEXT,
  "is_federation_approved" BOOLEAN,
  "license_number" TEXT,
  "registration_date" TEXT,
  "country" TEXT,
  "city" TEXT,
  "address" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "website" TEXT,
  "social_media" JSONB,
  "age_groups" JSONB,
  "sports_facilities" JSONB,
  "number_of_coaches" BIGINT,
  "training_programs" TEXT,
  "achievements" TEXT,
  "license_file" TEXT,
  "facility_photos" JSONB,
  "director" JSONB,
  "technical_director" JSONB,
  "main_branch" JSONB,
  "branches" JSONB,
  "academy_goals" TEXT,
  "success_stories" JSONB,
  "partnerships" JSONB,
  "stats" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "accountType" TEXT,
  "isVerified" BOOLEAN,
  "isPremium" BOOLEAN,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "isDeleted" BOOLEAN,
  "isActive" BOOLEAN,
  "deletedBy" TEXT,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "emailUpdated" BOOLEAN,
  "firebaseEmail" TEXT,
  "name" TEXT,
  "gallery" JSONB,
  "established" TEXT,
  "license" TEXT,
  "programs" JSONB,
  "facebook" TEXT,
  "twitter" TEXT,
  "instagram" TEXT,
  "facilities" JSONB,
  "programs_offered" JSONB,
  "staff" JSONB,
  "following" JSONB,
  "savedVideos" JSONB,
  "followersCount" BIGINT,
  "followers" JSONB,
  "uid" TEXT,
  "profile_image" TEXT,
  "full_name" TEXT,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "created_at" JSONB,
  "likedVideos" JSONB,
  "statusChangedAt" TIMESTAMP WITH TIME ZONE,
  "statusChangedBy" TEXT,
  "lastLoginIP" TEXT,
  "lastLogin" TIMESTAMP WITH TIME ZONE,
  "last_login" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "academys" (
  "id" TEXT PRIMARY KEY,
  "uid" TEXT,
  "email" TEXT,
  "accountType" TEXT,
  "full_name" TEXT,
  "profile_image" TEXT,
  "isNewUser" BOOLEAN,
  "created_at" JSONB,
  "updated_at" JSONB,
  "country" TEXT,
  "countryCode" TEXT,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "firebaseEmail" TEXT,
  "originalPhone" TEXT,
  "originalEmail" TEXT,
  "previousPhone" TEXT,
  "phone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "isActive" BOOLEAN,
  "organizationCode" TEXT,
  "isDeleted" BOOLEAN,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "deletedBy" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT,
  "verificationStatus" TEXT,
  "verifiedAt" TIMESTAMP WITH TIME ZONE,
  "verifiedBy" TEXT
);

CREATE TABLE IF NOT EXISTS "adminLogs" (
  "id" TEXT PRIMARY KEY,
  "adminId" TEXT,
  "action" TEXT,
  "description" TEXT,
  "metadata" JSONB,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "admin_notifications" (
  "id" TEXT PRIMARY KEY,
  "message" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "paymentData" JSONB,
  "title" TEXT,
  "paymentId" TEXT,
  "type" TEXT,
  "isRead" BOOLEAN,
  "priority" TEXT,
  "employeeId" TEXT,
  "employeeName" TEXT,
  "employeeEmail" TEXT,
  "actionType" TEXT,
  "targetType" TEXT,
  "targetId" TEXT,
  "metadata" JSONB
);

CREATE TABLE IF NOT EXISTS "admins" (
  "id" TEXT PRIMARY KEY,
  "role" TEXT,
  "phone" TEXT,
  "permissions" JSONB,
  "name" TEXT,
  "isActive" BOOLEAN,
  "email" TEXT,
  "loginCount" BIGINT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "emergencyAccess" BOOLEAN,
  "lastEmergencyLogin" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "ads" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "ctaText" TEXT,
  "targetAudience" TEXT,
  "maxDisplays" BIGINT,
  "displayFrequency" TEXT,
  "showCloseButton" BOOLEAN,
  "autoClose" BIGINT,
  "showProgressBar" BOOLEAN,
  "urgency" TEXT,
  "discount" TEXT,
  "countdown" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "popupType" TEXT,
  "priority" BIGINT,
  "customUrl" TEXT,
  "displayDelay" BIGINT,
  "type" TEXT,
  "mediaUrl" TEXT,
  "ctaUrl" TEXT,
  "description" TEXT,
  "clicks" BIGINT,
  "views" BIGINT,
  "endDate" TEXT,
  "startDate" TEXT,
  "isActive" BOOLEAN,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "displayLocation" TEXT
);

CREATE TABLE IF NOT EXISTS "agents" (
  "id" TEXT PRIMARY KEY,
  "full_name" TEXT,
  "country" TEXT,
  "countryCode" TEXT,
  "organizationCode" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "isVerifiedLocal" BOOLEAN,
  "uid" TEXT,
  "accountType" TEXT,
  "profile_image" TEXT,
  "isNewUser" BOOLEAN,
  "isActive" BOOLEAN,
  "created_at" JSONB,
  "createdAt" JSONB,
  "updated_at" JSONB,
  "updatedAt" JSONB,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "firebaseEmail" TEXT,
  "originalPhone" TEXT,
  "lastLogin" JSONB,
  "last_login" JSONB,
  "lastLoginIP" TEXT,
  "followers" JSONB,
  "originalEmail" TEXT,
  "emailUpdated" BOOLEAN,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "followersCount" BIGINT,
  "isDeleted" BOOLEAN,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "date_of_birth" TEXT,
  "nationality" TEXT,
  "current_location" TEXT,
  "is_fifa_licensed" BOOLEAN,
  "license_number" TEXT,
  "license_expiry" TEXT,
  "years_of_experience" BIGINT,
  "specialization" TEXT,
  "spoken_languages" JSONB,
  "office_address" TEXT,
  "website" TEXT,
  "social_media" JSONB,
  "current_players" JSONB,
  "past_players" JSONB,
  "notable_deals" TEXT,
  "id_copy" TEXT,
  "license_copy" TEXT,
  "player_contracts_sample" TEXT,
  "stats" JSONB,
  "isVerified" BOOLEAN,
  "isPremium" BOOLEAN,
  "profile_photo" TEXT,
  "coverImage" TEXT,
  "statusChangedBy" TEXT,
  "statusChangedAt" TIMESTAMP WITH TIME ZONE,
  "previousPhone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT
);

CREATE TABLE IF NOT EXISTS "analytics" (
  "id" TEXT PRIMARY KEY,
  "event" TEXT,
  "route" TEXT,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  "sessionId" TEXT,
  "country" TEXT,
  "city" TEXT,
  "ip" TEXT,
  "userAgent" TEXT,
  "page" TEXT,
  "device" TEXT,
  "processed" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "analytics_visits" (
  "id" TEXT PRIMARY KEY,
  "route" TEXT,
  "geo" JSONB,
  "ip" TEXT,
  "userAgent" TEXT,
  "sessionId" TEXT,
  "event" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "backup_otps" (
  "id" TEXT PRIMARY KEY,
  "phoneNumber" TEXT,
  "otp" TEXT,
  "expiresAt" TIMESTAMP WITH TIME ZONE,
  "verified" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "bulkPayments" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT,
  "userName" TEXT,
  "userEmail" TEXT,
  "accountType" TEXT,
  "paymentMethod" TEXT,
  "packageType" TEXT,
  "amount" BIGINT,
  "currency" TEXT,
  "playerCount" BIGINT,
  "transactionId" TEXT,
  "senderName" TEXT,
  "senderAccount" TEXT,
  "receiptUrl" TEXT,
  "description" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "players" JSONB,
  "metadata" JSONB,
  "updatedBy" TEXT,
  "status" TEXT,
  "subscription_expires_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "subscription_status" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "careerApplications" (
  "id" TEXT PRIMARY KEY,
  "fullName" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "country" TEXT,
  "governorate" TEXT,
  "experience" TEXT,
  "linkedin" TEXT,
  "facebook" TEXT,
  "notes" TEXT,
  "roles" JSONB,
  "role" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "status" TEXT
);

CREATE TABLE IF NOT EXISTS "careers_applications" (
  "id" TEXT PRIMARY KEY,
  "fullName" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "country" TEXT,
  "governorate" TEXT,
  "experience" TEXT,
  "linkedin" TEXT,
  "facebook" TEXT,
  "notes" TEXT,
  "roles" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "cities" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "countryCode" TEXT,
  "isCapital" BOOLEAN,
  "isActive" BOOLEAN,
  "userCount" BIGINT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "clubs" (
  "id" TEXT PRIMARY KEY,
  "followers" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "uid" TEXT,
  "accountType" TEXT,
  "full_name" TEXT,
  "phone" TEXT,
  "profile_image" TEXT,
  "isNewUser" BOOLEAN,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "country" TEXT,
  "countryCode" TEXT,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "originalPhone" TEXT,
  "originalEmail" TEXT,
  "emailUpdated" BOOLEAN,
  "firebaseEmail" TEXT,
  "email" TEXT,
  "isDeleted" BOOLEAN,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "previousPhone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "website" TEXT,
  "address" TEXT,
  "manager" TEXT,
  "city" TEXT,
  "isVerified" BOOLEAN,
  "facebook" TEXT,
  "founded" TEXT,
  "description" TEXT,
  "instagram" TEXT,
  "type" TEXT,
  "academies" JSONB,
  "twitter" TEXT,
  "stats" JSONB,
  "schools" JSONB,
  "name" TEXT,
  "isPremium" BOOLEAN,
  "trophies" JSONB,
  "gallery" JSONB,
  "board" JSONB,
  "coverImage" TEXT,
  "logo" TEXT,
  "statusChangedAt" TIMESTAMP WITH TIME ZONE,
  "isActive" BOOLEAN,
  "statusChangedBy" TEXT,
  "followersCount" BIGINT,
  "organizationCode" TEXT,
  "isVerifiedLocal" BOOLEAN,
  "lastLogin" JSONB,
  "last_login" JSONB,
  "lastLoginIP" TEXT,
  "likedVideos" JSONB,
  "following" JSONB,
  "savedVideos" JSONB,
  "registrationDate" TIMESTAMP WITH TIME ZONE,
  "cover" TEXT,
  "favorites" JSONB
);

CREATE TABLE IF NOT EXISTS "content" (
  "id" TEXT PRIMARY KEY,
  "siteName" TEXT,
  "darkLogoUrl" TEXT,
  "footerLogoUrl" TEXT,
  "slogan" TEXT,
  "logoUrl" TEXT,
  "items" JSONB
);

CREATE TABLE IF NOT EXISTS "conversations" (
  "id" TEXT PRIMARY KEY,
  "participants" JSONB,
  "participantNames" JSONB,
  "participantTypes" JSONB,
  "lastMessage" TEXT,
  "lastSenderId" TEXT,
  "isActive" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "lastMessageTime" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "unreadCount" JSONB,
  "participantAvatars" JSONB,
  "subject" TEXT
);

CREATE TABLE IF NOT EXISTS "countries" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "code" TEXT,
  "currency" TEXT,
  "phoneCode" TEXT,
  "flag" TEXT,
  "isActive" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "customers" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "type" TEXT,
  "group" TEXT,
  "date" TIMESTAMP WITH TIME ZONE,
  "status" TEXT,
  "country" TEXT,
  "countryCode" TEXT,
  "displayName" TEXT,
  "isMyContact" BOOLEAN,
  "savedName" TEXT,
  "groupName" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "contactStatus" TEXT,
  "lastActionBy" TEXT,
  "contactCount" BIGINT,
  "contactHistory" JSONB,
  "lastContactDate" TIMESTAMP WITH TIME ZONE,
  "lastAction" TEXT,
  "lastActionDate" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "dream_academy_categories" (
  "id" TEXT PRIMARY KEY,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "basePriceUSD" BIGINT,
  "titleEn" TEXT,
  "currency" TEXT,
  "allowedPaymentMethods" JSONB,
  "isActive" BOOLEAN,
  "title" TEXT,
  "titleAr" TEXT,
  "group" TEXT,
  "color" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "dream_academy_sources" (
  "id" TEXT PRIMARY KEY,
  "provider" TEXT,
  "sourceType" TEXT,
  "url" TEXT,
  "categoryId" TEXT,
  "order" BIGINT,
  "isActive" BOOLEAN,
  "title" TEXT,
  "resolvedTitle" TEXT,
  "resolvedDescription" TEXT,
  "durationSec" BIGINT,
  "channelTitle" TEXT,
  "thumbnailUrl" TEXT,
  "videoId" TEXT,
  "playlistId" TEXT,
  "createdBy" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "dream_academy_stats" (
  "id" TEXT PRIMARY KEY,
  "likes" BIGINT,
  "views" BIGINT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "email_logs" (
  "id" TEXT PRIMARY KEY,
  "to" TEXT,
  "subject" TEXT,
  "type" TEXT,
  "status" TEXT,
  "resendId" TEXT,
  "userId" TEXT,
  "userName" TEXT,
  "metadata" JSONB,
  "sentAt" BIGINT,
  "error" TEXT
);

CREATE TABLE IF NOT EXISTS "employee_activities" (
  "id" TEXT PRIMARY KEY,
  "employeeId" TEXT,
  "action" TEXT,
  "details" JSONB,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  "performedBy" TEXT
);

CREATE TABLE IF NOT EXISTS "employees" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "role" TEXT,
  "department" TEXT,
  "regions" JSONB,
  "permissions" JSONB,
  "locations" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "authUserId" TEXT,
  "isActive" BOOLEAN,
  "avatar" TEXT,
  "workStartTime" TEXT,
  "workEndTime" TEXT,
  "loginMethods" JSONB,
  "uid" TEXT,
  "allowedCountries" JSONB,
  "phonePrefix" TEXT,
  "roleId" TEXT,
  "roleName" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "geidea_payments" (
  "id" TEXT PRIMARY KEY,
  "orderId" TEXT,
  "source" TEXT,
  "merchantReferenceId" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "geideaOrderId" TEXT,
  "callbackReceivedAt" TIMESTAMP WITH TIME ZONE,
  "currency" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "rawPayload" JSONB,
  "transactionId" TEXT,
  "paidAt" TIMESTAMP WITH TIME ZONE,
  "paymentMethod" TEXT,
  "status" TEXT,
  "amount" BIGINT,
  "ourMerchantReferenceId" TEXT,
  "customerEmail" TEXT,
  "fetchedFromGeideaAt" TIMESTAMP WITH TIME ZONE,
  "customerPhone" TEXT,
  "customerName" TEXT
);

CREATE TABLE IF NOT EXISTS "geidea_settings" (
  "id" TEXT PRIMARY KEY,
  "mode" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "interaction_notifications" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "viewerId" TEXT,
  "userId" TEXT,
  "isRead" BOOLEAN,
  "viewerAccountType" TEXT,
  "viewerName" TEXT,
  "actionUrl" TEXT,
  "viewerType" TEXT,
  "message" TEXT,
  "priority" TEXT,
  "emoji" TEXT,
  "expiresAt" TIMESTAMP WITH TIME ZONE,
  "metadata" JSONB,
  "type" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "profileOwnerId" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "videoId" TEXT
);

CREATE TABLE IF NOT EXISTS "invoices" (
  "id" TEXT PRIMARY KEY,
  "paymentId" TEXT,
  "transactionId" TEXT,
  "amount" TEXT,
  "currency" TEXT,
  "status" TEXT,
  "provider" TEXT,
  "originalStatus" TEXT,
  "userId" TEXT,
  "metadata" TEXT,
  "package_name" TEXT,
  "packageName" TEXT,
  "plan_name" TEXT,
  "packageType" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "invoice_number" TEXT,
  "customerName" TEXT,
  "customerEmail" TEXT,
  "country" TEXT,
  "method" TEXT,
  "paymentMethod" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "packageDuration" TEXT,
  "package_duration" TEXT,
  "playerCount" BIGINT,
  "players" JSONB,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "paidAt" TIMESTAMP WITH TIME ZONE,
  "receiptUrl" TEXT,
  "notes" TEXT,
  "rejectionDate" TIMESTAMP WITH TIME ZONE,
  "payment_id" TEXT,
  "user_id" TEXT,
  "user_name" TEXT,
  "user_email" TEXT
);

CREATE TABLE IF NOT EXISTS "join_request_notifications" (
  "id" TEXT PRIMARY KEY,
  "message" TEXT,
  "organizationId" TEXT,
  "requestId" TEXT,
  "playerName" TEXT,
  "type" TEXT,
  "organizationType" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "playerId" TEXT,
  "isRead" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "marketers" (
  "id" TEXT PRIMARY KEY,
  "uid" TEXT,
  "email" TEXT,
  "accountType" TEXT,
  "full_name" TEXT,
  "phone" TEXT,
  "profile_image" TEXT,
  "isNewUser" BOOLEAN,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "country" TEXT,
  "countryCode" TEXT,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "firebaseEmail" TEXT,
  "originalPhone" TEXT,
  "originalEmail" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "isActive" BOOLEAN,
  "organizationCode" TEXT,
  "previousPhone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT,
  "updatedAt" JSONB,
  "lastLogin" JSONB,
  "last_login" JSONB,
  "lastLoginIP" TEXT,
  "isVerifiedLocal" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" TEXT PRIMARY KEY,
  "conversationId" TEXT,
  "senderId" TEXT,
  "receiverId" TEXT,
  "senderName" TEXT,
  "receiverName" TEXT,
  "senderType" TEXT,
  "receiverType" TEXT,
  "message" TEXT,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  "isRead" BOOLEAN,
  "messageType" TEXT,
  "deliveryStatus" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "readAt" TIMESTAMP WITH TIME ZONE,
  "subject" TEXT,
  "type" TEXT,
  "content" TEXT,
  "recipientPhone" TEXT,
  "recipientEmail" TEXT,
  "status" TEXT,
  "paymentId" TEXT,
  "channel" TEXT,
  "voiceDuration" BIGINT,
  "isPinned" BOOLEAN,
  "imageUrl" TEXT,
  "voiceUrl" TEXT,
  "read" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "message" TEXT,
  "type" TEXT,
  "priority" TEXT,
  "isRead" BOOLEAN,
  "scope" TEXT,
  "metadata" JSONB,
  "userId" TEXT,
  "userEmail" TEXT,
  "userPhone" TEXT,
  "senderId" TEXT,
  "senderName" TEXT,
  "senderAccountType" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "body" TEXT,
  "senderType" TEXT,
  "conversationId" TEXT,
  "link" TEXT,
  "category" TEXT,
  "paymentId" TEXT,
  "status" TEXT,
  "sentAt" TIMESTAMP WITH TIME ZONE,
  "sentVia" TEXT,
  "senderAvatar" TEXT,
  "messageId" TEXT,
  "read" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "organization_referrals" (
  "id" TEXT PRIMARY KEY,
  "organizationId" TEXT,
  "organizationType" TEXT,
  "organizationName" TEXT,
  "referralCode" TEXT,
  "inviteLink" TEXT,
  "description" TEXT,
  "isActive" BOOLEAN,
  "currentUsage" BIGINT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "maxUsage" BIGINT
);

CREATE TABLE IF NOT EXISTS "otp_codes" (
  "id" TEXT PRIMARY KEY,
  "phoneNumber" TEXT,
  "otp" TEXT,
  "expiresAt" TIMESTAMP WITH TIME ZONE,
  "verified" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "verifiedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "otp_verifications" (
  "id" TEXT PRIMARY KEY,
  "phoneNumber" TEXT,
  "otpHash" TEXT,
  "attempts" BIGINT,
  "expiresAt" TIMESTAMP WITH TIME ZONE,
  "verified" BOOLEAN,
  "purpose" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "otps" (
  "id" TEXT PRIMARY KEY,
  "otp" TEXT,
  "timestamp" BIGINT,
  "attempts" BIGINT,
  "expired" BOOLEAN,
  "source" TEXT,
  "originalPhone" TEXT
);

CREATE TABLE IF NOT EXISTS "partners" (
  "id" TEXT PRIMARY KEY,
  "partnerName" TEXT,
  "partnerCode" TEXT,
  "partnerType" TEXT,
  "status" TEXT,
  "isPublic" BOOLEAN,
  "customPricing" JSONB,
  "activeSubscriptions" BIGINT,
  "totalRevenue" BIGINT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "passwordResetTokens" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT,
  "userId" TEXT,
  "collection" TEXT,
  "createdAt" BIGINT,
  "expiresAt" BIGINT,
  "used" BOOLEAN,
  "usedAt" BIGINT
);

CREATE TABLE IF NOT EXISTS "payment_action_logs" (
  "id" TEXT PRIMARY KEY,
  "paymentId" TEXT,
  "userId" TEXT,
  "userName" TEXT,
  "action" TEXT,
  "details" TEXT,
  "adminId" TEXT,
  "metadata" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedBy" TEXT,
  "status" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "payment_results" (
  "id" TEXT PRIMARY KEY,
  "orderId" TEXT,
  "merchantReferenceId" TEXT,
  "amount" BIGINT,
  "currency" TEXT,
  "status" TEXT,
  "paymentMethod" TEXT,
  "cardBrand" TEXT,
  "createdDate" TIMESTAMP WITH TIME ZONE,
  "updatedDate" TIMESTAMP WITH TIME ZONE,
  "processedAt" TIMESTAMP WITH TIME ZONE,
  "webhookReceived" BOOLEAN,
  "isTest" BOOLEAN,
  "transactions" JSONB,
  "fullWebhookData" JSONB
);

CREATE TABLE IF NOT EXISTS "payment_settings" (
  "id" TEXT PRIMARY KEY,
  "countryCode" TEXT,
  "countryName" TEXT,
  "currency" TEXT,
  "methods" JSONB
);

CREATE TABLE IF NOT EXISTS "player_action_logs" (
  "id" TEXT PRIMARY KEY,
  "playerId" TEXT,
  "action" TEXT,
  "actionBy" TEXT,
  "actionByType" TEXT,
  "details" JSONB,
  "metadata" JSONB,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "player_join_requests" (
  "id" TEXT PRIMARY KEY,
  "playerId" TEXT,
  "playerName" TEXT,
  "playerEmail" TEXT,
  "playerPhone" TEXT,
  "organizationId" TEXT,
  "organizationType" TEXT,
  "organizationName" TEXT,
  "referralCode" TEXT,
  "requestedAt" TIMESTAMP WITH TIME ZONE,
  "playerData" JSONB,
  "notes" TEXT,
  "processedAt" TIMESTAMP WITH TIME ZONE,
  "processedBy" TEXT,
  "status" TEXT
);

CREATE TABLE IF NOT EXISTS "player_notifications" (
  "id" TEXT PRIMARY KEY,
  "playerId" TEXT,
  "organizationId" TEXT,
  "organizationName" TEXT,
  "type" TEXT,
  "message" TEXT,
  "isRead" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "player_rewards" (
  "id" TEXT PRIMARY KEY,
  "playerId" TEXT,
  "totalPoints" BIGINT,
  "availablePoints" BIGINT,
  "totalEarnings" BIGINT,
  "referralCount" BIGINT,
  "badges" JSONB,
  "lastUpdated" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "player_stats" (
  "id" TEXT PRIMARY KEY,
  "profileViews" BIGINT,
  "videoViews" BIGINT,
  "matches" BIGINT,
  "goals" BIGINT,
  "assists" BIGINT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "players" (
  "id" TEXT PRIMARY KEY,
  "uid" TEXT,
  "originalPhone" TEXT,
  "countryCode" TEXT,
  "accountType" TEXT,
  "originalEmail" TEXT,
  "currencySymbol" TEXT,
  "country" TEXT,
  "created_at" JSONB,
  "isNewUser" BOOLEAN,
  "phone" TEXT,
  "currency" TEXT,
  "full_name" TEXT,
  "emailUpdated" BOOLEAN,
  "firebaseEmail" TEXT,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "whatsapp" TEXT,
  "sports_notes" TEXT,
  "achievements" JSONB,
  "injuries" JSONB,
  "city" TEXT,
  "birth_date" TEXT,
  "videos" JSONB,
  "club_history" JSONB,
  "medical_history" JSONB,
  "medical_notes" TEXT,
  "contract_history" JSONB,
  "chronic_conditions" BOOLEAN,
  "email" TEXT,
  "brief" TEXT,
  "address" TEXT,
  "agent_history" JSONB,
  "training_courses" JSONB,
  "surgeries" JSONB,
  "previous_clubs" JSONB,
  "nationality" TEXT,
  "current_club" TEXT,
  "chronic_details" TEXT,
  "currently_contracted" TEXT,
  "spanish_level" TEXT,
  "english_level" TEXT,
  "graduation_year" TEXT,
  "degree" TEXT,
  "education_level" TEXT,
  "arabic_level" TEXT,
  "allergies" TEXT,
  "blood_type" TEXT,
  "weight" TEXT,
  "height" TEXT,
  "favorite_jersey_number" TEXT,
  "player_number" TEXT,
  "experience_years" TEXT,
  "preferred_foot" TEXT,
  "has_passport" TEXT,
  "ref_source" TEXT,
  "primary_position" TEXT,
  "secondary_position" TEXT,
  "technical_skills" JSONB,
  "social_skills" JSONB,
  "physical_skills" JSONB,
  "objectives" JSONB,
  "official_contact" JSONB,
  "additional_images" JSONB,
  "documents" JSONB,
  "profile_image_url" TEXT,
  "profile_image" JSONB,
  "updated_at" JSONB,
  "createdAt" JSONB,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "isDeleted" BOOLEAN,
  "previousPhone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "isActive" BOOLEAN,
  "organizationCode" TEXT,
  "isVerifiedLocal" BOOLEAN,
  "mentality_aggression" BIGINT,
  "stats_dribbling" BIGINT,
  "contract_status" TEXT,
  "allergies_list" JSONB,
  "mentality_composure" BIGINT,
  "medications" JSONB,
  "stats_physical" BIGINT,
  "jersey_number" TEXT,
  "mentality_vision" BIGINT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "courses" JSONB,
  "work_rate_attack" TEXT,
  "images" JSONB,
  "work_rate_defense" TEXT,
  "skill_moves" BIGINT,
  "mentality_teamwork" BIGINT,
  "academies" JSONB,
  "weak_foot" BIGINT,
  "has_private_coach" BOOLEAN,
  "name" TEXT,
  "position" TEXT,
  "stats_shooting" BIGINT,
  "guardian_name" TEXT,
  "gender" TEXT,
  "social_links" JSONB,
  "private_coaches" JSONB,
  "stats_defending" BIGINT,
  "foot" TEXT,
  "mentality_leadership" BIGINT,
  "stats_pace" BIGINT,
  "languages" JSONB,
  "has_joined_academy" BOOLEAN,
  "stats_passing" BIGINT,
  "surgeries_list" JSONB,
  "guardian_phone" TEXT,
  "statusChangedBy" TEXT,
  "statusChangedAt" TIMESTAMP WITH TIME ZONE,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT,
  "whatsappCountryCode" TEXT,
  "phoneNumber" TEXT,
  "whatsappCountry" TEXT,
  "phoneVerified" BOOLEAN,
  "profileUpdateRequested" BOOLEAN,
  "trainerId" TEXT,
  "subscription_status" TEXT,
  "subscription_type" TEXT,
  "subscription_end" TIMESTAMP WITH TIME ZONE,
  "organizationId" TEXT,
  "organizationType" TEXT,
  "organizationJoinedAt" TIMESTAMP WITH TIME ZONE,
  "joinRequestId" TEXT,
  "joinedViaReferral" BOOLEAN,
  "academy_id" TEXT,
  "organizationName" TEXT,
  "joinRequestStatus" TEXT,
  "organizationApprovedBy" JSONB,
  "referralCodeUsed" TEXT,
  "trainer_id" TEXT,
  "academyId" TEXT,
  "firebaseUid" TEXT,
  "convertedToAccount" BOOLEAN,
  "tempPassword" TEXT,
  "convertedAt" TIMESTAMP WITH TIME ZONE,
  "updated_by" TEXT,
  "updated_by_type" TEXT,
  "created_by" TEXT,
  "created_by_type" TEXT,
  "club_id" TEXT,
  "clubId" TEXT,
  "deletedBy" TEXT,
  "likedVideos" JSONB,
  "video_urls" JSONB,
  "agent_id" TEXT,
  "agentId" TEXT,
  "willing_to_relocate" BOOLEAN,
  "available_for_transfer" BOOLEAN,
  "agent_name" TEXT,
  "market_value" BIGINT,
  "school_name" TEXT,
  "agent_phone" TEXT,
  "lastLogin" TIMESTAMP WITH TIME ZONE,
  "last_login" TIMESTAMP WITH TIME ZONE,
  "lastLoginIP" TEXT,
  "verificationStatus" TEXT,
  "verifiedAt" TIMESTAMP WITH TIME ZONE,
  "verifiedBy" TEXT,
  "subscriptionExpiresAt" JSONB,
  "selectedPackage" TEXT,
  "subscriptionStatus" TEXT,
  "packageType" TEXT,
  "lastPaymentId" TEXT,
  "subscriptionEndDate" JSONB,
  "migratedFromUid" TEXT,
  "uploaded_videos" JSONB,
  "addedBy" JSONB,
  "following" JSONB,
  "savedVideos" JSONB,
  "loginAccountCreated" BOOLEAN,
  "hasLoginAccount" BOOLEAN,
  "registrationDate" TIMESTAMP WITH TIME ZONE,
  "additional_image_urls" JSONB,
  "user_id" TEXT,
  "strength" BIGINT,
  "stamina" BIGINT,
  "defending" DOUBLE PRECISION,
  "shooting" BIGINT,
  "concentration" DOUBLE PRECISION,
  "speed" DOUBLE PRECISION,
  "decision_making" DOUBLE PRECISION,
  "vision" BIGINT,
  "flexibility" BIGINT,
  "ball_control" BIGINT,
  "leadership" BIGINT,
  "passing" DOUBLE PRECISION,
  "emailMigratedAt" JSONB,
  "emailMigrationStatus" TEXT,
  "oldEmail" TEXT,
  "chronic_conditions_details" TEXT,
  "media" JSONB,
  "has_chronic_conditions" BOOLEAN,
  "years_experience" TEXT,
  "reactivated_at" JSONB,
  "image" TEXT,
  "contract_end_date" TEXT,
  "accountTypeChangedBy" TEXT,
  "previousAccountType" TEXT,
  "accountTypeChangedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "private_sessions_requests" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "whatsapp" TEXT,
  "durationMinutes" BIGINT,
  "notes" TEXT,
  "currency" TEXT,
  "amount" BIGINT,
  "paymentMethod" TEXT,
  "categoryId" TEXT,
  "paymentStatus" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "real-time-stats" (
  "id" TEXT PRIMARY KEY,
  "last_package" TEXT,
  "last_update" TIMESTAMP WITH TIME ZONE,
  "update_count" BIGINT
);

CREATE TABLE IF NOT EXISTS "real-time-updates" (
  "id" TEXT PRIMARY KEY,
  "package" JSONB,
  "admin_id" TEXT,
  "action" TEXT,
  "currency" TEXT,
  "type" TEXT,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "receipts" (
  "id" TEXT PRIMARY KEY,
  "invoiceId" TEXT,
  "url" TEXT,
  "userId" TEXT,
  "status" TEXT,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "referrals" (
  "id" TEXT PRIMARY KEY,
  "referrerId" TEXT,
  "referredId" TEXT,
  "referralCode" TEXT,
  "status" TEXT,
  "rewards" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "roles" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "permissions" JSONB,
  "isSystem" BOOLEAN,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "security_logs" (
  "id" TEXT PRIMARY KEY,
  "event" TEXT,
  "details" JSONB,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  "environment" TEXT,
  "userAgent" TEXT,
  "ipAddress" TEXT,
  "location" TEXT
);

CREATE TABLE IF NOT EXISTS "settings" (
  "id" TEXT PRIMARY KEY,
  "referralRewardPercentage" BIGINT,
  "newUserDiscountPercentage" BIGINT,
  "maxReferralReward" BIGINT,
  "minSubscriptionForReward" BIGINT,
  "isActive" BOOLEAN,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "smart_notifications" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "message" TEXT,
  "priority" TEXT,
  "type" TEXT,
  "isRead" BOOLEAN,
  "metadata" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "userId" TEXT,
  "viewerId" TEXT,
  "viewerName" TEXT,
  "viewerType" TEXT,
  "emoji" TEXT,
  "actionUrl" TEXT,
  "expiresAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "subtitle" TEXT,
  "period" TEXT,
  "base_currency" TEXT,
  "base_original_price" BIGINT,
  "base_price" BIGINT,
  "features" JSONB,
  "bonusFeatures" JSONB,
  "popular" BOOLEAN,
  "icon" TEXT,
  "color" TEXT,
  "overrides" JSONB,
  "isActive" BOOLEAN,
  "order" BIGINT
);

CREATE TABLE IF NOT EXISTS "subscriptions" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT,
  "plan_name" TEXT,
  "package_name" TEXT,
  "package_duration" TEXT,
  "package_price" BIGINT,
  "payment_id" TEXT,
  "activated_at" TIMESTAMP WITH TIME ZONE,
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "status" TEXT,
  "features" JSONB,
  "invoice_number" TEXT,
  "receipt_url" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "packageType" TEXT,
  "end_date" TIMESTAMP WITH TIME ZONE,
  "startDate" TIMESTAMP WITH TIME ZONE,
  "endDate" TIMESTAMP WITH TIME ZONE,
  "paymentMethod" TEXT,
  "amount" BIGINT,
  "currency" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "is_auto_renew" BOOLEAN,
  "payment_method" TEXT,
  "start_date" TIMESTAMP WITH TIME ZONE,
  "paidAmount" BIGINT,
  "receiptInfo" JSONB,
  "autoRenew" BOOLEAN,
  "transaction_id" TEXT,
  "customer_name" TEXT,
  "customer_email" TEXT,
  "customer_phone" TEXT,
  "billing_address" TEXT,
  "tax_number" TEXT,
  "payment_date" TEXT,
  "user_id" TEXT,
  "auto_renew" BOOLEAN,
  "packageName" TEXT,
  "packageDuration" TEXT,
  "packagePrice" BIGINT,
  "paymentId" TEXT,
  "activatedAt" TIMESTAMP WITH TIME ZONE,
  "expiresAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "support_conversations" (
  "id" TEXT PRIMARY KEY,
  "category" TEXT,
  "priority" TEXT,
  "unreadCount" BIGINT,
  "userName" TEXT,
  "status" TEXT,
  "userId" TEXT,
  "userType" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "lastMessage" TEXT,
  "lastMessageTime" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "userEmail" TEXT,
  "userPhone" TEXT,
  "subject" TEXT
);

CREATE TABLE IF NOT EXISTS "support_messages" (
  "id" TEXT PRIMARY KEY,
  "conversationId" TEXT,
  "senderId" TEXT,
  "senderName" TEXT,
  "senderType" TEXT,
  "message" TEXT,
  "isRead" BOOLEAN,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "support_notifications" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT,
  "message" TEXT,
  "status" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "system_configs" (
  "id" TEXT PRIMARY KEY,
  "baseUrl" TEXT,
  "senderName" TEXT,
  "apiKey" TEXT,
  "defaultCountryCode" TEXT,
  "isActive" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "test" (
  "id" TEXT PRIMARY KEY,
  "test" BOOLEAN,
  "message" TEXT,
  "timestamp" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "tournamentRegistrations" (
  "id" TEXT PRIMARY KEY,
  "tournamentId" TEXT,
  "tournamentName" TEXT,
  "players" JSONB,
  "accountType" TEXT,
  "accountEmail" TEXT,
  "accountPhone" TEXT,
  "organizationType" TEXT,
  "paymentMethod" TEXT,
  "mobileWalletProvider" TEXT,
  "mobileWalletNumber" TEXT,
  "receiptUrl" TEXT,
  "receiptNumber" TEXT,
  "paymentAmount" BIGINT,
  "paymentStatus" TEXT,
  "notes" TEXT,
  "registrationType" TEXT,
  "registrationDate" TIMESTAMP WITH TIME ZONE,
  "status" TEXT,
  "createdBy" TEXT,
  "accountName" TEXT,
  "organizationName" TEXT,
  "selectedPlayers" JSONB
);

CREATE TABLE IF NOT EXISTS "tournament_registrations" (
  "id" TEXT PRIMARY KEY,
  "tournamentId" TEXT,
  "playerId" TEXT,
  "playerName" TEXT,
  "playerEmail" TEXT,
  "playerPhone" TEXT,
  "registrationDate" TIMESTAMP WITH TIME ZONE,
  "paymentStatus" TEXT,
  "paymentAmount" BIGINT,
  "notes" TEXT,
  "registrationType" TEXT,
  "accountType" TEXT,
  "accountEmail" TEXT,
  "accountPhone" TEXT,
  "organizationType" TEXT,
  "paymentMethod" TEXT,
  "mobileWalletProvider" TEXT,
  "mobileWalletNumber" TEXT,
  "receiptUrl" TEXT,
  "receiptNumber" TEXT,
  "clubContact" TEXT,
  "playerAge" BIGINT,
  "playerClub" TEXT,
  "playerPosition" TEXT,
  "clubName" TEXT,
  "clubPlayers" JSONB,
  "paymentType" TEXT,
  "userId" TEXT,
  "players" JSONB,
  "totalAmount" BIGINT,
  "currency" TEXT,
  "status" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "playerBirthDate" TEXT,
  "accountName" TEXT,
  "organizationName" TEXT,
  "walletProvider" TEXT,
  "paymentDate" TIMESTAMP WITH TIME ZONE,
  "updatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS "tournaments" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT,
  "description" TEXT,
  "location" TEXT,
  "maxParticipants" BIGINT,
  "currentParticipants" BIGINT,
  "isPaid" BOOLEAN,
  "ageGroups" JSONB,
  "categories" JSONB,
  "logo" TEXT,
  "paymentDeadline" TEXT,
  "maxPlayersPerClub" BIGINT,
  "registrations" JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "contactInfo" TEXT,
  "prizes" TEXT,
  "refundPolicy" TEXT,
  "rules" TEXT,
  "currency" TEXT,
  "locationUrl" TEXT,
  "installmentsDetails" TEXT,
  "installmentsCount" BIGINT,
  "allowInstallments" BOOLEAN,
  "isActive" BOOLEAN,
  "registrationDeadline" TEXT,
  "paymentMethods" JSONB,
  "entryFee" BIGINT,
  "walletName" TEXT,
  "feeType" TEXT,
  "walletNumber" TEXT,
  "endDate" TEXT,
  "startDate" TEXT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "country" TEXT
);

CREATE TABLE IF NOT EXISTS "trainers" (
  "id" TEXT PRIMARY KEY,
  "uid" TEXT,
  "accountType" TEXT,
  "full_name" TEXT,
  "profile_image" TEXT,
  "isNewUser" BOOLEAN,
  "created_at" JSONB,
  "updated_at" JSONB,
  "country" TEXT,
  "countryCode" TEXT,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "originalPhone" TEXT,
  "originalEmail" TEXT,
  "emailUpdated" BOOLEAN,
  "firebaseEmail" TEXT,
  "email" TEXT,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "followers" JSONB,
  "previousPhone" TEXT,
  "phone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "createdAt" JSONB,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT,
  "achievements" TEXT,
  "references" TEXT,
  "profile_photo" TEXT,
  "is_certified" BOOLEAN,
  "id_copy" TEXT,
  "license_copy" TEXT,
  "date_of_birth" TEXT,
  "description" TEXT,
  "license_expiry" TEXT,
  "years_of_experience" BIGINT,
  "license_number" TEXT,
  "previous_clubs" JSONB,
  "spoken_languages" JSONB,
  "coaching_level" TEXT,
  "cv" TEXT,
  "nationality" TEXT,
  "stats" JSONB,
  "coverImage" TEXT,
  "specialization" TEXT,
  "current_location" TEXT,
  "social_media" JSONB,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "isVerified" BOOLEAN,
  "isPremium" BOOLEAN,
  "followersCount" BIGINT,
  "isActive" BOOLEAN,
  "organizationCode" TEXT,
  "isVerifiedLocal" BOOLEAN,
  "isDeleted" BOOLEAN,
  "deletedBy" TEXT,
  "accountTypeChangedBy" TEXT,
  "previousAccountType" TEXT,
  "accountTypeChangedAt" TIMESTAMP WITH TIME ZONE,
  "rejectedBy" TEXT,
  "verificationStatus" TEXT,
  "rejectedAt" TIMESTAMP WITH TIME ZONE,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "lastLogin" JSONB,
  "last_login" JSONB,
  "lastLoginIP" TEXT
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT PRIMARY KEY,
  "uid" TEXT,
  "originalEmail" TEXT,
  "currency" TEXT,
  "currencySymbol" TEXT,
  "full_name" TEXT,
  "originalPhone" TEXT,
  "countryCode" TEXT,
  "isNewUser" BOOLEAN,
  "country" TEXT,
  "accountType" TEXT,
  "phone" TEXT,
  "oldEmail" TEXT,
  "emailMigratedAt" TIMESTAMP WITH TIME ZONE,
  "emailMigrationStatus" TEXT,
  "sports_notes" TEXT,
  "achievements" JSONB,
  "documents" JSONB,
  "injuries" JSONB,
  "technical_skills" JSONB,
  "birth_date" TEXT,
  "experience_years" TEXT,
  "videos" JSONB,
  "isActive" BOOLEAN,
  "medical_history" JSONB,
  "official_contact" JSONB,
  "medical_notes" TEXT,
  "profile_image" JSONB,
  "chronic_conditions" BOOLEAN,
  "physical_skills" JSONB,
  "height" TEXT,
  "additional_images" JSONB,
  "training_courses" JSONB,
  "favorite_jersey_number" TEXT,
  "graduation_year" TEXT,
  "degree" TEXT,
  "weight" TEXT,
  "has_passport" TEXT,
  "ref_source" TEXT,
  "spanish_level" TEXT,
  "emailUpdatedAt" TIMESTAMP WITH TIME ZONE,
  "nationality" TEXT,
  "current_club" TEXT,
  "education_level" TEXT,
  "allergies" TEXT,
  "whatsapp" TEXT,
  "city" TEXT,
  "club_history" JSONB,
  "contract_history" JSONB,
  "player_number" TEXT,
  "blood_type" TEXT,
  "preferred_foot" TEXT,
  "primary_position" TEXT,
  "email" TEXT,
  "brief" TEXT,
  "address" TEXT,
  "agent_history" JSONB,
  "emailUpdated" BOOLEAN,
  "surgeries" JSONB,
  "profile_image_url" TEXT,
  "english_level" TEXT,
  "previous_clubs" JSONB,
  "social_skills" JSONB,
  "firebaseEmail" TEXT,
  "objectives" JSONB,
  "secondary_position" TEXT,
  "arabic_level" TEXT,
  "chronic_details" TEXT,
  "currently_contracted" TEXT,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE,
  "registrationDate" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "isDeleted" BOOLEAN,
  "deletedBy" TEXT,
  "deletedAt" TIMESTAMP WITH TIME ZONE,
  "previousEmail" TEXT,
  "lastLogin" TIMESTAMP WITH TIME ZONE,
  "lastLoginIP" TEXT,
  "organizationCode" TEXT,
  "isVerifiedLocal" BOOLEAN,
  "phoneNumber" TEXT,
  "displayName" TEXT,
  "isProfileComplete" BOOLEAN,
  "mentality_aggression" BIGINT,
  "stats_dribbling" BIGINT,
  "contract_status" TEXT,
  "allergies_list" JSONB,
  "mentality_composure" BIGINT,
  "medications" JSONB,
  "stats_physical" BIGINT,
  "jersey_number" TEXT,
  "mentality_vision" BIGINT,
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  "courses" JSONB,
  "work_rate_attack" TEXT,
  "images" JSONB,
  "work_rate_defense" TEXT,
  "skill_moves" BIGINT,
  "mentality_teamwork" BIGINT,
  "academies" JSONB,
  "weak_foot" BIGINT,
  "has_private_coach" BOOLEAN,
  "name" TEXT,
  "position" TEXT,
  "stats_shooting" BIGINT,
  "guardian_name" TEXT,
  "gender" TEXT,
  "social_links" JSONB,
  "private_coaches" JSONB,
  "stats_defending" BIGINT,
  "foot" TEXT,
  "mentality_leadership" BIGINT,
  "stats_pace" BIGINT,
  "languages" JSONB,
  "has_joined_academy" BOOLEAN,
  "stats_passing" BIGINT,
  "surgeries_list" JSONB,
  "guardian_phone" TEXT,
  "agreeToTerms" BOOLEAN,
  "statusChangedBy" TEXT,
  "statusChangedAt" TIMESTAMP WITH TIME ZONE,
  "confirmPassword" TEXT,
  "password" TEXT,
  "isGoogleUser" BOOLEAN,
  "googleId" TEXT,
  "last_login" TIMESTAMP WITH TIME ZONE,
  "whatsappCountryCode" TEXT,
  "whatsappCountry" TEXT,
  "phoneVerified" BOOLEAN,
  "profileUpdateRequested" BOOLEAN,
  "isVerified" BOOLEAN,
  "description" TEXT,
  "training_programs" TEXT,
  "main_branch" JSONB,
  "sports_facilities" JSONB,
  "partnerships" JSONB,
  "success_stories" JSONB,
  "stats" JSONB,
  "coverImage" TEXT,
  "facility_photos" JSONB,
  "logo" TEXT,
  "number_of_coaches" BIGINT,
  "website" TEXT,
  "director" JSONB,
  "academy_name" TEXT,
  "branches" JSONB,
  "is_federation_approved" BOOLEAN,
  "license_file" TEXT,
  "license_number" TEXT,
  "academy_goals" TEXT,
  "registration_date" TEXT,
  "academy_type" TEXT,
  "age_groups" JSONB,
  "technical_director" JSONB,
  "founding_year" TEXT,
  "isPremium" BOOLEAN,
  "social_media" JSONB,
  "employeeId" TEXT,
  "roleName" TEXT,
  "permissions" JSONB,
  "department" TEXT,
  "lastSyncedAt" TIMESTAMP WITH TIME ZONE,
  "subscriptionStatus" TEXT,
  "selectedPackage" TEXT,
  "packageType" TEXT,
  "subscriptionExpiresAt" TIMESTAMP WITH TIME ZONE,
  "subscriptionEndDate" TIMESTAMP WITH TIME ZONE,
  "lastPaymentId" TEXT,
  "references" TEXT,
  "is_certified" BOOLEAN,
  "date_of_birth" TEXT,
  "license_expiry" TEXT,
  "years_of_experience" BIGINT,
  "coaching_level" TEXT,
  "current_location" TEXT,
  "profile_photo" TEXT,
  "id_copy" TEXT,
  "license_copy" TEXT,
  "spoken_languages" JSONB,
  "cv" TEXT,
  "followers" JSONB,
  "specialization" TEXT,
  "lastPaymentDate" TIMESTAMP WITH TIME ZONE,
  "lastPaymentAmount" BIGINT,
  "lastPaymentMethod" TEXT,
  "passwordLastUpdated" TIMESTAMP WITH TIME ZONE,
  "userEmail" TEXT,
  "academy_id" TEXT,
  "verified" BOOLEAN,
  "profileCompleted" BOOLEAN,
  "tempPassword" TEXT,
  "needsPasswordChange" BOOLEAN,
  "convertedFromDependent" BOOLEAN,
  "originalSource" TEXT,
  "unifiedPassword" BOOLEAN,
  "convertedAt" TIMESTAMP WITH TIME ZONE,
  "organizationApprovedBy" JSONB,
  "organizationId" TEXT,
  "organizationName" TEXT,
  "joinRequestStatus" TEXT,
  "organizationJoinedAt" TIMESTAMP WITH TIME ZONE,
  "referralCodeUsed" TEXT,
  "joinedViaReferral" BOOLEAN,
  "organizationType" TEXT,
  "joinRequestId" TEXT,
  "allowedCountries" JSONB,
  "lastLoginLocation" TEXT,
  "role" TEXT,
  "roleId" TEXT,
  "employeeRole" TEXT,
  "avatar" TEXT,
  "lastLoginDevice" TEXT,
  "loginCount" BIGINT,
  "profileViews" BIGINT,
  "lastViewedAt" TIMESTAMP WITH TIME ZONE,
  "instagram" TEXT,
  "type" TEXT,
  "twitter" TEXT,
  "trophies" JSONB,
  "gallery" JSONB,
  "manager" TEXT,
  "facebook" TEXT,
  "founded" TEXT,
  "schools" JSONB,
  "board" JSONB,
  "photoURL" TEXT,
  "isSynced" BOOLEAN,
  "suspensionReason" TEXT,
  "suspendedAt" TIMESTAMP WITH TIME ZONE,
  "suspensionEndDate" TIMESTAMP WITH TIME ZONE,
  "likedVideos" JSONB,
  "agent_name" TEXT,
  "market_value" BIGINT,
  "school_name" TEXT,
  "agent_phone" TEXT,
  "club_id" TEXT,
  "verificationStatus" TEXT,
  "verifiedAt" TIMESTAMP WITH TIME ZONE,
  "verifiedBy" TEXT,
  "migratedFromUid" TEXT,
  "settings" JSONB,
  "trainer_id" TEXT,
  "subscription" JSONB,
  "agent_id" TEXT,
  "previousPhone" TEXT,
  "phoneFixed" BOOLEAN,
  "phoneFixedAt" TIMESTAMP WITH TIME ZONE,
  "phoneFixDescription" TEXT,
  "phoneNormalized" TEXT,
  "emergencyAccess" BOOLEAN,
  "lastEmergencyAccess" TIMESTAMP WITH TIME ZONE,
  "isAdmin" BOOLEAN,
  "followersCount" BIGINT
);

CREATE TABLE IF NOT EXISTS "video_action_logs" (
  "0" TEXT,
  "1" TEXT,
  "2" TEXT,
  "3" TEXT,
  "4" TEXT,
  "5" TEXT,
  "6" TEXT,
  "7" TEXT,
  "8" TEXT,
  "9" TEXT,
  "10" TEXT,
  "11" TEXT,
  "12" TEXT,
  "13" TEXT,
  "14" TEXT,
  "15" TEXT,
  "16" TEXT,
  "17" TEXT,
  "18" TEXT,
  "19" TEXT,
  "20" TEXT,
  "21" TEXT,
  "22" TEXT,
  "23" TEXT,
  "24" TEXT,
  "25" TEXT,
  "26" TEXT,
  "27" TEXT,
  "28" TEXT,
  "29" TEXT,
  "30" TEXT,
  "31" TEXT,
  "32" TEXT,
  "33" TEXT,
  "34" TEXT,
  "35" TEXT,
  "36" TEXT,
  "37" TEXT,
  "38" TEXT,
  "39" TEXT,
  "40" TEXT,
  "41" TEXT,
  "42" TEXT,
  "43" TEXT,
  "44" TEXT,
  "45" TEXT,
  "46" TEXT,
  "47" TEXT,
  "48" TEXT,
  "49" TEXT,
  "50" TEXT,
  "51" TEXT,
  "52" TEXT,
  "53" TEXT,
  "54" TEXT,
  "55" TEXT,
  "56" TEXT,
  "57" TEXT,
  "58" TEXT,
  "59" TEXT,
  "60" TEXT,
  "61" TEXT,
  "62" TEXT,
  "63" TEXT,
  "64" TEXT,
  "65" TEXT,
  "66" TEXT,
  "67" TEXT,
  "68" TEXT,
  "69" TEXT,
  "70" TEXT,
  "71" TEXT,
  "72" TEXT,
  "73" TEXT,
  "74" TEXT,
  "75" TEXT,
  "76" TEXT,
  "77" TEXT,
  "78" TEXT,
  "79" TEXT,
  "80" TEXT,
  "id" TEXT PRIMARY KEY,
  "action" TEXT,
  "videoId" TEXT,
  "playerId" TEXT,
  "actionBy" TEXT,
  "actionByType" TEXT,
  "details" JSONB,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  "metadata" JSONB
);

