org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.jvmargs=-Xmx1280m -XX:+UseParallelGC -XX:TieredStopAtLevel=1
kotlin.daemon.jvmargs=-Xmx512m -XX:+UseParallelGC
kotlin.incremental=false
org.gradle.workers.max=2
android.useAndroidX=true

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
