
var LG=['en','ar','fr','es','pt'],LI=0;
try{var sv0=localStorage.getItem('mk_lang');if(sv0&&LG.indexOf(sv0)>-1)LI=LG.indexOf(sv0)}catch(e){}
var A1="<a href='#svc' style='color:var(--gold);font-weight:600'>",A2="<a href='#offices' style='color:var(--gold);font-weight:600'>";
var D5={
ttl:["El7lm | Football talent discovery with AI","الحلم | منصة اكتشاف مواهب كرة القدم","El7lm | Découverte de talents du football par l'IA","El7lm | Descubrimiento de talentos del fútbol con IA","El7lm | Descoberta de talentos do futebol com IA"],
br:["El7lm","الحلم","El7lm","El7lm","El7lm"],
n_svc:["What we do","ما نقدمه","Nos services","Qué hacemos","O que fazemos"],
n_nasr:["Nisr","نسر","Nisr","Nisr","Nisr"],
n_off:["Offices","مكاتبنا","Bureaux","Oficinas","Escritórios"],
n_ct:["Contact","تواصل","Contact","Contacto","Contacto"],
h1a:["From Qatar","من قطر","Du Qatar","Desde Qatar","Do Qatar"],
h1b:["to the world","إلى العالم","au monde","para el mundo","para o mundo"],
h_cta:["Discover the platform →","اكتشف المنصة ←","Découvrir la plateforme →","Descubre la plataforma →","Descubra a plataforma →"],
h_tag:["Level up. Find your chance. Build your future.","طوّر مستواك. اكتشف فرصك. وابنِ مستقبلك.","Progressez. Saisissez vos chances. Construisez votre avenir.","Mejora tu nivel. Descubre tus oportunidades. Construye tu futuro.","Evolua. Descubra as suas oportunidades. Construa o seu futuro."],
pv_p:["Pause video","إيقاف الفيديو مؤقتاً","Mettre la vidéo en pause","Pausar el video","Pausar o vídeo"],
pv_r:["Play video","تشغيل الفيديو","Lire la vidéo","Reproducir el video","Reproduzir o vídeo"],
s_lbl:["(What we do)","(ما نقدمه)","(Nos services)","(Qué hacemos)","(O que fazemos)"],
s_h:["A smart assistant for discovering football talent","مساعد ذكي لاكتشاف مواهب كرة القدم","Un assistant intelligent pour découvrir les talents du football","Un asistente inteligente para descubrir talentos del fútbol","Um assistente inteligente para descobrir talentos do futebol"],
s_p:["The integrated digital platform for managing and developing football talent. We connect players with accredited clubs and offer smart advice powered by the Nisr AI model.","المنصة الرقمية المتكاملة لإدارة وتطوير مواهب كرة القدم. تربط اللاعبين بالأندية المعتمدة وتقدم استشارات ذكية مدعومة بنموذج Nisr AI.","La plateforme numérique intégrée pour gérer et développer les talents du football. Nous relions les joueurs aux clubs agréés et proposons des conseils intelligents grâce au modèle Nisr AI.","La plataforma digital integral para gestionar y desarrollar talentos del fútbol. Conectamos a los jugadores con clubes acreditados y ofrecemos asesoramiento inteligente basado en el modelo Nisr AI.","A plataforma digital integrada para gerir e desenvolver talentos do futebol. Ligamos jogadores a clubes credenciados e oferecemos aconselhamento inteligente com o modelo Nisr AI."],
v1:["Opportunities & trials","الفرص والمعاينات","Opportunités et essais","Oportunidades y pruebas","Oportunidades e testes"],
v2:["Club services","خدمات الأندية","Services pour les clubs","Servicios para clubes","Serviços para clubes"],
v3:["Academy services","خدمات الأكاديميات","Services pour les académies","Servicios para academias","Serviços para academias"],
v4:["Coaches & staff","المدربون والكوادر","Entraîneurs et staff","Entrenadores y cuerpo técnico","Treinadores e equipas técnicas"],
v5:["Player agents","وكلاء اللاعبين","Agents de joueurs","Agentes de jugadores","Agentes de jogadores"],
v6:["AI performance analysis","تحليل الأداء بالذكاء الاصطناعي","Analyse de performance par IA","Análisis de rendimiento con IA","Análise de desempenho com IA"],
v7:["Training & nutrition plans","خطط التدريب والتغذية","Plans d'entraînement et de nutrition","Planes de entrenamiento y nutrición","Planos de treino e nutrição"],
v8:["Professional match evaluation","مباريات وتقييم احترافي","Évaluation professionnelle des matchs","Evaluación profesional de partidos","Avaliação profissional de jogos"],
na_lbl:["(Nisr)","(نسر)","(Nisr)","(Nisr)","(Nisr)"],
na_h:["Your smart personal coach","مدربك الشخصي الذكي","Votre coach personnel intelligent","Tu entrenador personal inteligente","O seu treinador pessoal inteligente"],
na_p:["Nisr is an assistant built for players. It knows your position and level, answers your training questions and suggests your next step.","نسر مساعد مخصص للاعبين. يعرف مركزك ومستواك، ويجيب عن أسئلة تدريبك ويقترح عليك الخطوة التالية.","Nisr est un assistant conçu pour les joueurs. Il connaît votre poste et votre niveau, répond à vos questions d'entraînement et vous suggère la prochaine étape.","Nisr es un asistente creado para jugadores. Conoce tu posición y tu nivel, responde tus dudas de entrenamiento y te sugiere el siguiente paso.","O Nisr é um assistente criado para jogadores. Conhece a sua posição e o seu nível, responde às suas dúvidas de treino e sugere o próximo passo."],
c1:["Training plan","خطة التدريب","Plan d'entraînement","Plan de entrenamiento","Plano de treino"],
c2:["Nutrition plan","نظام غذائي","Plan nutritionnel","Plan nutricional","Plano nutricional"],
c3:["Skills development","تطوير المهارات","Développement des compétences","Desarrollo de habilidades","Desenvolvimento de competências"],
na_l:["Available in five languages","متاح بخمس لغات","Disponible en cinq langues","Disponible en cinco idiomas","Disponível em cinco idiomas"],
na_d:["Get Nisr on your phone","حمّل نسر على هاتفك","Téléchargez Nisr sur votre téléphone","Descarga Nisr en tu teléfono","Descarregue o Nisr no seu telemóvel"],
soon:["Coming soon","قريباً","Bientôt","Próximamente","Em breve"],
app_alt:["The Nisr assistant screen in the El7lm app","شاشة المساعد الذكي نسر في تطبيق الحلم","L'écran de l'assistant Nisr dans l'application El7lm","La pantalla del asistente Nisr en la app El7lm","O ecrã do assistente Nisr na aplicação El7lm"],
logo_alt:["El7lm logo","شعار الحلم","Logo El7lm","Logotipo de El7lm","Logótipo da El7lm"],
p_lbl:["(Partners)","(شركاؤنا)","(Partenaires)","(Socios)","(Parceiros)"],
p_h:["Partner clubs","الأندية الشريكة","Clubs partenaires","Clubes asociados","Clubes parceiros"],
crest_alt:["Illustrative club crest","شعار نادٍ تخيلي","Blason de club fictif","Escudo de club ficticio","Emblema de clube fictício"],
o_lbl:["(Offices)","(مكاتبنا)","(Bureaux)","(Oficinas)","(Escritórios)"],
o_h:["Present on three continents","حاضرون في ثلاث قارات","Présents sur trois continents","Presentes en tres continentes","Presentes em três continentes"],
o_p:["Qatar, Egypt, Saudi Arabia, Morocco, Portugal, Spain and Senegal.","قطر ومصر والسعودية والمغرب والبرتغال وإسبانيا والسنغال.","Qatar, Égypte, Arabie saoudite, Maroc, Portugal, Espagne et Sénégal.","Catar, Egipto, Arabia Saudita, Marruecos, Portugal, España y Senegal.","Catar, Egito, Arábia Saudita, Marrocos, Portugal, Espanha e Senegal."],
o_btn:["Explore the globe →","استكشف الكرة الأرضية ←","Explorer le globe →","Explorar el globo →","Explorar o globo →"],
f_lbl:["(FAQ)","(الأسئلة الشائعة)","(FAQ)","(Preguntas frecuentes)","(Perguntas frequentes)"],
f_h:["Questions & answers","أسئلة وأجوبة","Questions et réponses","Preguntas y respuestas","Perguntas e respostas"],
q1:["How does a talented player reach clubs?","كيف يصل اللاعب الموهوب إلى الأندية؟","Comment un joueur talentueux atteint-il les clubs ?","¿Cómo llega un jugador talentoso a los clubes?","Como chega um jogador talentoso aos clubes?"],
a1:["The platform connects players with accredited clubs and opens the door to opportunities and trials through the Opportunities & Trials service.","تربط المنصة اللاعبين بالأندية المعتمدة، وتفتح لهم باب الفرص والمعاينات من خلال خدمة الفرص والمعاينات.","La plateforme met les joueurs en relation avec des clubs agréés et leur ouvre les portes des opportunités et des essais grâce au service Opportunités et essais.","La plataforma conecta a los jugadores con clubes acreditados y les abre la puerta a oportunidades y pruebas a través del servicio de Oportunidades y pruebas.","A plataforma liga os jogadores a clubes credenciados e abre-lhes a porta a oportunidades e testes através do serviço Oportunidades e testes."],
q2:["How does a player improve before clubs notice them?","كيف يتطور اللاعب قبل أن تكتشفه الأندية؟","Comment un joueur progresse-t-il avant d'être repéré par les clubs ?","¿Cómo mejora un jugador antes de que lo descubran los clubes?","Como evolui um jogador antes de ser notado pelos clubes?"],
a2:["Nisr, the smart personal coach in the app, suggests a training plan and a nutrition plan, and helps develop skills and analyse performance.","يرافقه نسر، المدرب الشخصي الذكي داخل التطبيق. يقترح عليه خطة التدريب والنظام الغذائي، ويساعده في تطوير مهاراته وتحليل أدائه.","Nisr, le coach personnel intelligent de l'application, propose un plan d'entraînement et un plan nutritionnel, et aide à développer les compétences et à analyser les performances.","Nisr, el entrenador personal inteligente de la app, propone un plan de entrenamiento y uno de nutrición, y ayuda a desarrollar habilidades y analizar el rendimiento.","O Nisr, o treinador pessoal inteligente da aplicação, sugere um plano de treino e um plano nutricional e ajuda a desenvolver competências e a analisar o desempenho."],
q3:["What does the platform offer clubs?","ماذا تقدم المنصة للأندية؟","Que propose la plateforme aux clubs ?","¿Qué ofrece la plataforma a los clubes?","O que oferece a plataforma aos clubes?"],
a3:["It lets clubs reach and discover football talent, and provides smart advice powered by the Nisr AI model.","تتيح للأندية الوصول إلى مواهب كرة القدم واكتشافها، وتقدم استشارات ذكية مدعومة بنموذج Nisr AI.","Elle permet aux clubs de repérer et de découvrir des talents du football, et fournit des conseils intelligents grâce au modèle Nisr AI.","Permite a los clubes llegar a talentos del fútbol y descubrirlos, y ofrece asesoramiento inteligente basado en el modelo Nisr AI.","Permite que os clubes cheguem aos talentos do futebol e os descubram, e oferece aconselhamento inteligente com o modelo Nisr AI."],
q4:["What about academies, coaches and agents?","وماذا عن الأكاديميات والمدربين ووكلاء اللاعبين؟","Et les académies, les entraîneurs et les agents ?","¿Y las academias, los entrenadores y los agentes?","E as academias, os treinadores e os agentes?"],
a4:["Each group has its own services: academy services, coaches & staff, and player agents. Find them in the "+A1+"What we do</a> section.","لكل فئة خدمات خاصة بها: خدمات الأكاديميات، والمدربون والكوادر، ووكلاء اللاعبين. تجدها في قسم "+A1+"ما نقدمه</a>.","Chaque groupe a ses propres services : services pour les académies, entraîneurs et staff, et agents de joueurs. Retrouvez-les dans la section "+A1+"Nos services</a>.","Cada grupo tiene sus propios servicios: servicios para academias, entrenadores y cuerpo técnico, y agentes de jugadores. Encuéntralos en la sección "+A1+"Qué hacemos</a>.","Cada grupo tem os seus próprios serviços: serviços para academias, treinadores e equipas técnicas, e agentes de jogadores. Encontre-os na secção "+A1+"O que fazemos</a>."],
q5:["How do I download the app?","كيف أحمّل التطبيق؟","Comment télécharger l'application ?","¿Cómo descargo la app?","Como descarrego a aplicação?"],
a5:["The app is available on Google Play. The App Store version is being uploaded and will be available soon.","التطبيق متاح على متجر Google Play. نسخة App Store قيد الرفع وستتوفر قريباً.","L'application est disponible sur Google Play. La version App Store est en cours de mise en ligne et sera bientôt disponible.","La app está disponible en Google Play. La versión de App Store se está subiendo y estará disponible próximamente.","A aplicação está disponível na Google Play. A versão para a App Store está a ser carregada e estará disponível em breve."],
q6:["Which languages are available?","ما اللغات المتاحة؟","Quelles langues sont disponibles ?","¿Qué idiomas hay disponibles?","Que idiomas estão disponíveis?"],
a6:["Arabic, English, French, Spanish and Portuguese.","العربية والإنجليزية والفرنسية والإسبانية والبرتغالية.","Arabe, anglais, français, espagnol et portugais.","Árabe, inglés, francés, español y portugués.","Árabe, inglês, francês, espanhol e português."],
q7:["Where are your offices?","أين توجد مكاتبكم؟","Où sont vos bureaux ?","¿Dónde están sus oficinas?","Onde ficam os vossos escritórios?"],
a7:["Our headquarters are in the Qatar Financial Centre in Doha, with offices in Egypt, Saudi Arabia, Morocco, Portugal, Spain and Senegal. See the "+A2+"Offices</a> page for details.","مقرنا الرئيسي في مركز قطر للمال بالدوحة، ولنا مكاتب في مصر والسعودية والمغرب والبرتغال وإسبانيا والسنغال. تجد التفاصيل في صفحة "+A2+"مكاتبنا</a>.","Notre siège principal se trouve au Centre financier du Qatar à Doha, avec des bureaux en Égypte, en Arabie saoudite, au Maroc, au Portugal, en Espagne et au Sénégal. Consultez la page "+A2+"Bureaux</a> pour plus de détails.","Nuestra sede central está en el Centro Financiero de Catar, en Doha, con oficinas en Egipto, Arabia Saudita, Marruecos, Portugal, España y Senegal. Consulta la página de "+A2+"Oficinas</a> para más detalles.","A nossa sede principal fica no Centro Financeiro do Catar, em Doha, com escritórios no Egito, na Arábia Saudita, em Marrocos, em Portugal, em Espanha e no Senegal. Consulte a página "+A2+"Escritórios</a> para mais detalhes."],
q8:["How can I contact you?","كيف أتواصل معكم؟","Comment vous contacter ?","¿Cómo puedo contactarlos?","Como posso contactá-los?"],
a8:["Message us on WhatsApp or write to info@el7lm.com, or use the buttons at the bottom of the page.","راسلنا عبر واتساب أو على البريد info@el7lm.com، أو استخدم الأزرار في أسفل الصفحة.","Écrivez-nous sur WhatsApp ou à info@el7lm.com, ou utilisez les boutons en bas de la page.","Escríbenos por WhatsApp o a info@el7lm.com, o usa los botones al final de la página.","Envie-nos uma mensagem no WhatsApp ou escreva para info@el7lm.com, ou use os botões no fundo da página."],
of_p:["Click any dot on the globe, or pick a country from the list, to see the office details.","اضغط على أي نقطة في الكرة الأرضية، أو اختر دولة من القائمة، لتعرف تفاصيل المكتب.","Cliquez sur un point du globe ou choisissez un pays dans la liste pour voir les détails du bureau.","Haz clic en cualquier punto del globo o elige un país de la lista para ver los detalles de la oficina.","Clique em qualquer ponto do globo ou escolha um país na lista para ver os detalhes do escritório."],
gl_a:["Interactive globe showing El7lm office locations","كرة أرضية تفاعلية تعرض مواقع مكاتب الحلم","Globe interactif montrant les bureaux de El7lm","Globo interactivo con las oficinas de El7lm","Globo interativo com os escritórios da El7lm"],
c_qa:["Qatar","قطر","Qatar","Catar","Catar"],c_eg:["Egypt","مصر","Égypte","Egipto","Egito"],c_sa:["Saudi Arabia","السعودية","Arabie saoudite","Arabia Saudita","Arábia Saudita"],c_ma:["Morocco","المغرب","Maroc","Marruecos","Marrocos"],c_pt:["Portugal","البرتغال","Portugal","Portugal","Portugal"],c_es:["Spain","إسبانيا","Espagne","España","Espanha"],c_sn:["Senegal","السنغال","Sénégal","Senegal","Senegal"],
ci_qa:["Doha","الدوحة","Doha","Doha","Doha"],ci_eg:["Cairo","القاهرة","Le Caire","El Cairo","Cairo"],ci_sa:["Riyadh","الرياض","Riyad","Riad","Riade"],ci_ma:["Rabat","الرباط","Rabat","Rabat","Rabat"],
ad_qa:["Qatar Financial Centre, 9th floor","مركز قطر للمال، الدور التاسع","Centre financier du Qatar, 9e étage","Centro Financiero de Catar, planta 9","Centro Financeiro do Catar, 9.º andar"],
ad_eg:["Nasr City, Mostafa El-Nahas","مدينة نصر، مصطفى النحاس","Nasr City, Mostafa El-Nahas","Nasr City, Mostafa El-Nahas","Nasr City, Mostafa El-Nahas"],
ad_sa:["King Fahd Road","طريق الملك فهد","Route du Roi Fahd","Carretera del Rey Fahd","Estrada Rei Fahd"],
hqtag:["Headquarters","المقر الرئيسي","Siège principal","Sede central","Sede principal"],
addr_na:["Office address coming soon","عنوان المكتب قيد الإضافة","Adresse du bureau bientôt disponible","Dirección de la oficina próximamente","Morada do escritório em breve"],
call:["Call us","اتصل بنا","Appelez-nous","Llámanos","Ligue-nos"],
pg_l:["(El7lm)","(منصة الحلم)","(El7lm)","(El7lm)","(El7lm)"],
pg_c:["Contact us","تواصل معنا","Nous contacter","Contáctanos","Contacte-nos"],
pg_b:["Back to home","العودة للرئيسية","Retour à l'accueil","Volver al inicio","Voltar ao início"],
pt_about:["About El7lm","عن منصة الحلم","À propos de El7lm","Sobre El7lm","Sobre a El7lm"],
pt_jobs:["Careers","الوظائف والفرص الوظيفية","Carrières","Empleo","Carreiras"],
pt_priv:["Privacy policy","سياسة الخصوصية","Politique de confidentialité","Política de privacidad","Política de privacidade"],
pt_terms:["Terms & conditions","الشروط والأحكام","Conditions générales","Términos y condiciones","Termos e condições"],
pb_opps:["The platform connects players with accredited clubs and opens the door to opportunities and trials. Download the app and talk to Nisr to learn your next step.","تربط المنصة اللاعبين بالأندية المعتمدة وتفتح لهم باب الفرص والمعاينات. حمّل التطبيق وتحدّث مع نسر لتعرف خطوتك التالية.","La plateforme met les joueurs en relation avec des clubs agréés et leur ouvre la porte des opportunités et des essais. Téléchargez l'application et discutez avec Nisr pour connaître votre prochaine étape.","La plataforma conecta a los jugadores con clubes acreditados y les abre la puerta a oportunidades y pruebas. Descarga la app y habla con Nisr para conocer tu próximo paso.","A plataforma liga os jogadores a clubes credenciados e abre-lhes a porta a oportunidades e testes. Descarregue a aplicação e fale com o Nisr para saber o seu próximo passo."],
pb_clubs:["The platform lets clubs reach and discover football talent, and provides smart advice powered by the Nisr AI model.","تتيح المنصة للأندية الوصول إلى مواهب كرة القدم واكتشافها، وتقدّم استشارات ذكية مدعومة بنموذج Nisr AI.","La plateforme permet aux clubs de repérer et de découvrir des talents du football, et offre des conseils intelligents grâce au modèle Nisr AI.","La plataforma permite a los clubes llegar a talentos del fútbol y descubrirlos, y ofrece asesoramiento inteligente basado en el modelo Nisr AI.","A plataforma permite que os clubes cheguem aos talentos do futebol e os descubram, e oferece aconselhamento inteligente com o modelo Nisr AI."],
pb_academies:["Digital services for academies to develop their players' talent and connect them with clubs.","خدمات رقمية للأكاديميات لتطوير مواهب اللاعبين وربطهم بالأندية.","Des services numériques pour aider les académies à développer le talent de leurs joueurs et à les mettre en relation avec des clubs.","Servicios digitales para que las academias desarrollen el talento de sus jugadores y los conecten con clubes.","Serviços digitais para as academias desenvolverem o talento dos seus jogadores e os ligarem a clubes."],
pb_coaches:["Services for coaches and technical staff within the platform's player-development ecosystem.","خدمات للمدربين والكوادر الفنية ضمن منظومة تطوير اللاعبين على المنصة.","Des services pour les entraîneurs et le staff technique au sein de l'écosystème de développement des joueurs de la plateforme.","Servicios para entrenadores y cuerpo técnico dentro del ecosistema de desarrollo de jugadores de la plataforma.","Serviços para treinadores e equipas técnicas no ecossistema de desenvolvimento de jogadores da plataforma."],
pb_agents:["Services for player agents to reach talent and clubs through the platform.","خدمات لوكلاء اللاعبين للوصول إلى المواهب والأندية عبر المنصة.","Des services permettant aux agents de joueurs d'accéder aux talents et aux clubs via la plateforme.","Servicios para que los agentes de jugadores lleguen a talentos y clubes a través de la plataforma.","Serviços para os agentes de jogadores chegarem a talentos e clubes através da plataforma."],
pb_about:["The integrated digital platform for managing and developing football talent. We connect players with accredited clubs and offer smart advice powered by the Nisr AI model. Our headquarters are in the Qatar Financial Centre, Doha.","المنصة الرقمية المتكاملة لإدارة وتطوير مواهب كرة القدم، تربط اللاعبين بالأندية المعتمدة وتقدّم استشارات ذكية مدعومة بنموذج Nisr AI. مقرنا الرئيسي في مركز قطر للمال بالدوحة.","La plateforme numérique intégrée pour gérer et développer les talents du football. Nous relions les joueurs aux clubs agréés et proposons des conseils intelligents grâce au modèle Nisr AI. Notre siège principal se trouve au Centre financier du Qatar, à Doha.","La plataforma digital integral para gestionar y desarrollar talentos del fútbol. Conectamos a los jugadores con clubes acreditados y ofrecemos asesoramiento inteligente basado en el modelo Nisr AI. Nuestra sede central está en el Centro Financiero de Catar, en Doha.","A plataforma digital integrada para gerir e desenvolver talentos do futebol. Ligamos jogadores a clubes credenciados e oferecemos aconselhamento inteligente com o modelo Nisr AI. A nossa sede principal fica no Centro Financeiro do Catar, em Doha."],
pb_jobs:["For questions about job opportunities or to apply, write to info@el7lm.com.","للاستفسار عن الفرص الوظيفية أو التقديم عليها، راسلنا على info@el7lm.com.","Pour toute question sur les offres d'emploi ou pour postuler, écrivez à info@el7lm.com.","Para consultas sobre oportunidades laborales o para postularte, escribe a info@el7lm.com.","Para questões sobre oportunidades de emprego ou para se candidatar, escreva para info@el7lm.com."],
pb_legal:["The official text of this page is being added.","النص الرسمي لهذه الصفحة قيد الإضافة.","Le texte officiel de cette page est en cours d'ajout.","El texto oficial de esta página se está añadiendo.","O texto oficial desta página está a ser adicionado."],
ft_big:["Let's start the dream together","لنبدأ الحلم معاً","Commençons le rêve ensemble","Empecemos el sueño juntos","Vamos começar o sonho juntos"],
ft_h1:["Services & opportunities","الخدمات والفرص","Services et opportunités","Servicios y oportunidades","Serviços e oportunidades"],
ft_h2:["Platform & support","المنصة والدعم","Plateforme et assistance","Plataforma y soporte","Plataforma e apoio"],
ft_h3:["Direct contact","تواصل مباشر","Contact direct","Contacto directo","Contacto direto"],
ft_faq:["FAQ","الأسئلة الشائعة","FAQ","Preguntas frecuentes","Perguntas frequentes"],
wa_q:["WhatsApp Qatar","واتساب قطر","WhatsApp Qatar","WhatsApp Catar","WhatsApp Catar"],
wa_e:["WhatsApp Egypt","واتساب مصر","WhatsApp Égypte","WhatsApp Egipto","WhatsApp Egito"],
avail:["Available 24/7","متاح 24/7","Disponible 24h/24, 7j/7","Disponible 24/7","Disponível 24/7"],
sponsor:["Call your personal sponsor","اتصال بالراعي الشخصي","Appeler votre parrain personnel","Llamar a tu patrocinador personal","Ligar ao seu patrocinador pessoal"],
copy:["© 2026 El7lm Sports Platform. All rights reserved.","© 2026 جميع الحقوق محفوظة لمنصة الحلم الرياضية.","© 2026 Plateforme sportive El7lm. Tous droits réservés.","© 2026 Plataforma deportiva El7lm. Todos los derechos reservados.","© 2026 Plataforma desportiva El7lm. Todos os direitos reservados."],
lic:["Accredited and licensed to serve the sports and youth sector","معتمدة ومرخصة لخدمة قطاع الرياضة والشباب","Agréée et autorisée à servir le secteur du sport et de la jeunesse","Acreditada y autorizada para servir al sector deportivo y juvenil","Credenciada e licenciada para servir o setor do desporto e da juventude"]
};

D5.more=["View details →","عرض التفاصيل ←","Voir les détails →","Ver detalles →","Ver detalhes →"];
D5.mn=["Menu","القائمة","Menu","Menú","Menu"];
D5.pop_t=["Get the El7lm app","حمّل تطبيق الحلم","Téléchargez l'application El7lm","Descarga la app de El7lm","Descarregue a aplicação El7lm"];
D5.pop_p=["Download the app and talk to Nisr, your smart personal coach, anytime.","حمّل التطبيق وتحدّث مع نسر، مدربك الشخصي الذكي، في أي وقت.","Téléchargez l'application et discutez à tout moment avec Nisr, votre coach personnel intelligent.","Descarga la app y habla con Nisr, tu entrenador personal inteligente, cuando quieras.","Descarregue a aplicação e fale com o Nisr, o seu treinador pessoal inteligente, a qualquer momento."];
D5.pop_n=["Maybe later","ليس الآن","Plus tard","Ahora no","Agora não"];
D5.pop_x=["Close","إغلاق","Fermer","Cerrar","Fechar"];
D5.s11=["Club trials","معاينات الأندية","Essais en club","Pruebas en clubes","Testes em clubes"];
D5.s12=["Professional opportunities","فرص الاحتراف","Opportunités professionnelles","Oportunidades profesionales","Oportunidades profissionais"];
D5.s13=["Player profile & visibility","ملف اللاعب وفرص الظهور","Profil du joueur et visibilité","Perfil del jugador y visibilidad","Perfil do jogador e visibilidade"];
D5.s21=["Talent discovery","اكتشاف المواهب","Détection de talents","Descubrimiento de talentos","Descoberta de talentos"];
D5.s22=["Player reports & analysis","تقارير وتحليل اللاعبين","Rapports et analyses de joueurs","Informes y análisis de jugadores","Relatórios e análise de jogadores"];
D5.s23=["Nisr AI advisory","استشارات Nisr AI","Conseil Nisr AI","Asesoramiento Nisr AI","Aconselhamento Nisr AI"];
D5.s31=["Player management","إدارة اللاعبين","Gestion des joueurs","Gestión de jugadores","Gestão de jogadores"];
D5.s32=["Talent development","تطوير المواهب","Développement des talents","Desarrollo de talentos","Desenvolvimento de talentos"];
D5.s33=["Links with clubs","الربط بالأندية","Liens avec les clubs","Conexión con clubes","Ligação a clubes"];
D5.s41=["Training tools","أدوات التدريب","Outils d'entraînement","Herramientas de entrenamiento","Ferramentas de treino"];
D5.s42=["Tracking player progress","متابعة تطور اللاعبين","Suivi de la progression des joueurs","Seguimiento del progreso de los jugadores","Acompanhamento da evolução dos jogadores"];
D5.s43=["Training plans","الخطط التدريبية","Plans d'entraînement","Planes de entrenamiento","Planos de treino"];
D5.s51=["Access to talent","الوصول إلى المواهب","Accès aux talents","Acceso a talentos","Acesso a talentos"];
D5.s52=["Contact with clubs","التواصل مع الأندية","Contact avec les clubs","Contacto con clubes","Contacto com clubes"];
D5.s53=["Player profiles","ملفات اللاعبين","Profils de joueurs","Perfiles de jugadores","Perfis de jogadores"];
D5.s61=["Video analysis","تحليل الفيديو","Analyse vidéo","Análisis de video","Análise de vídeo"];
D5.s62=["Performance indicators","مؤشرات الأداء","Indicateurs de performance","Indicadores de rendimiento","Indicadores de desempenho"];
D5.s63=["Progress reports","تقارير التطور","Rapports de progression","Informes de progreso","Relatórios de evolução"];
D5.s71=["Personalised training plan","خطة تدريب مخصصة","Plan d'entraînement personnalisé","Plan de entrenamiento personalizado","Plano de treino personalizado"];
D5.s72=["Nutrition programmes","برامج غذائية","Programmes nutritionnels","Programas de nutrición","Programas de nutrição"];
D5.s81=["Match video review","مراجعة فيديو المباريات","Revue vidéo des matchs","Revisión en video de partidos","Revisão em vídeo de jogos"];
D5.s82=["Professional rating","تقييم احترافي","Évaluation professionnelle","Valoración profesional","Avaliação profissional"];
D5.s83=["Post-match feedback","ملاحظات ما بعد المباراة","Retour après match","Comentarios posteriores al partido","Feedback pós-jogo"];
function tr(k,d){var a=D5[k];return a?a[LI]:(d===undefined?k:d)}
